import Link from "next/link"
import Head from "next/head"

import Navbar from "./Components/Navbar"
import Footer from "./Components/Footer" 

import Container from "./Components/Container"

const about = () => {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <Navbar />

            <Container>
                
            </Container>

            <Footer />
        </>
    )
}

export default about